/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelesRouteImport } from './routes/modeles'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedResumeNewRouteImport } from './routes/_authenticated/resume.new'
import { Route as AuthenticatedResumeIdEditRouteImport } from './routes/_authenticated/resume.$id.edit'
import { Route as AuthenticatedResumeIdPreviewRouteImport } from './routes/_authenticated/resume.$id.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelesRoute = ModelesRouteImport.update({
  id: '/modeles',
  path: '/modeles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeNewRoute = AuthenticatedResumeNewRouteImport.update({
  id: '/resume/new',
  path: '/resume/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeIdEditRoute =
  AuthenticatedResumeIdEditRouteImport.update({
    id: '/resume/$id/edit',
    path: '/resume/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumeIdPreviewRoute =
  AuthenticatedResumeIdPreviewRouteImport.update({
    id: '/resume/$id/preview',
    path: '/resume/$id/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/modeles': typeof ModelesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/tarifs': typeof TarifsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/resume/new': typeof AuthenticatedResumeNewRoute
  '/resume/$id/edit': typeof AuthenticatedResumeIdEditRoute
  '/resume/$id/preview': typeof AuthenticatedResumeIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/modeles': typeof ModelesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/tarifs': typeof TarifsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/resume/new': typeof AuthenticatedResumeNewRoute
  '/resume/$id/edit': typeof AuthenticatedResumeIdEditRoute
  '/resume/$id/preview': typeof AuthenticatedResumeIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/modeles': typeof ModelesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/resume/new': typeof AuthenticatedResumeNewRoute
  '/_authenticated/resume/$id/edit': typeof AuthenticatedResumeIdEditRoute
  '/_authenticated/resume/$id/preview': typeof AuthenticatedResumeIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/modeles'
    | '/reset-password'
    | '/signup'
    | '/tarifs'
    | '/dashboard'
    | '/resume/new'
    | '/resume/$id/edit'
    | '/resume/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/modeles'
    | '/reset-password'
    | '/signup'
    | '/tarifs'
    | '/dashboard'
    | '/resume/new'
    | '/resume/$id/edit'
    | '/resume/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/modeles'
    | '/reset-password'
    | '/signup'
    | '/tarifs'
    | '/_authenticated/dashboard'
    | '/_authenticated/resume/new'
    | '/_authenticated/resume/$id/edit'
    | '/_authenticated/resume/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ModelesRoute: typeof ModelesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modeles': {
      id: '/modeles'
      path: '/modeles'
      fullPath: '/modeles'
      preLoaderRoute: typeof ModelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume/new': {
      id: '/_authenticated/resume/new'
      path: '/resume/new'
      fullPath: '/resume/new'
      preLoaderRoute: typeof AuthenticatedResumeNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume/$id/edit': {
      id: '/_authenticated/resume/$id/edit'
      path: '/resume/$id/edit'
      fullPath: '/resume/$id/edit'
      preLoaderRoute: typeof AuthenticatedResumeIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume/$id/preview': {
      id: '/_authenticated/resume/$id/preview'
      path: '/resume/$id/preview'
      fullPath: '/resume/$id/preview'
      preLoaderRoute: typeof AuthenticatedResumeIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedResumeNewRoute: typeof AuthenticatedResumeNewRoute
  AuthenticatedResumeIdEditRoute: typeof AuthenticatedResumeIdEditRoute
  AuthenticatedResumeIdPreviewRoute: typeof AuthenticatedResumeIdPreviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedResumeNewRoute: AuthenticatedResumeNewRoute,
  AuthenticatedResumeIdEditRoute: AuthenticatedResumeIdEditRoute,
  AuthenticatedResumeIdPreviewRoute: AuthenticatedResumeIdPreviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ModelesRoute: ModelesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
